name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate Xcode project
      run: swift package generate-xcodeproj
    - name: Build
      run: xcodebuild build -sdk iphoneos -scheme 'FloatLabeledPhoneNumberTextField-Package'
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 12' -scheme 'FloatLabeledPhoneNumberTextField-Package'
